In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

op_file_2012 = "Opioid raw_data (2012).csv"
op_file_2013 = "Opioid raw_data (2013).csv"
op_file_2014 = "Opioid raw_data (2014).csv"
op_file_2015 = "Opioid raw_data (2015).csv"
op_file_2016 = "Opioid raw_data (2016).csv"

op_data_2012 = pd.read_csv(op_file_2012)
op_data_2013 = pd.read_csv(op_file_2013)
op_data_2014 = pd.read_csv(op_file_2014)
op_data_2015 = pd.read_csv(op_file_2015)
op_data_2016 = pd.read_csv(op_file_2016)

In [2]:
op_df_2012 = op_data_2012.dropna()
op_df_2013 = op_data_2013.dropna()
op_df_2014 = op_data_2014.dropna()
op_df_2015 = op_data_2015.dropna()
op_df_2016 = op_data_2016.dropna()

In [3]:
op_df_2012 = op_df_2012.set_index("Location")
op_df_2013 = op_df_2013.set_index("Location")
op_df_2014 = op_df_2014.set_index("Location")
op_df_2015 = op_df_2015.set_index("Location")
op_df_2016 = op_df_2016.set_index("Location")

In [4]:
op_2012 = op_df_2012.loc[["United States","Arizona", "Colorado", "Florida", "Washington"]]
op_2013 = op_df_2013.loc[["United States","Arizona", "Colorado", "Florida", "Washington"]]
op_2014 = op_df_2014.loc[["United States","Arizona", "Colorado", "Florida", "Washington"]]
op_2015 = op_df_2015.loc[["United States","Arizona", "Colorado", "Florida", "Washington"]]
op_2016 = op_df_2016.loc[["United States","Arizona", "Colorado", "Florida", "Washington"]]

In [5]:
op_2012_rn = op_2012.rename(columns={"Opioid Overdose Death Rate (Age-Adjusted)":"Opioid OD Death Rate (2012)", "Percent Change in Opioid Overdose Death Rate from Prior Year":"% Change in Opioid OD Death Rate from Prior Year (2012)"})
op_2013_rn = op_2013.rename(columns={"Opioid Overdose Death Rate (Age-Adjusted)":"Opioid OD Death Rate (2013)", "Percent Change in Opioid Overdose Death Rate from Prior Year":"% Change in Opioid OD Death Rate from Prior Year (2013)"})
op_2014_rn = op_2014.rename(columns={"Opioid Overdose Death Rate (Age-Adjusted)":"Opioid OD Death Rate (2014)", "Percent Change in Opioid Overdose Death Rate from Prior Year":"% Change in Opioid OD Death Rate from Prior Year (2014)"})
op_2015_rn = op_2015.rename(columns={"Opioid Overdose Death Rate (Age-Adjusted)":"Opioid OD Death Rate (2015)", "Percent Change in Opioid Overdose Death Rate from Prior Year":"% Change in Opioid OD Death Rate from Prior Year (2015)"})
op_2016_rn = op_2016.rename(columns={"Opioid Overdose Death Rate (Age-Adjusted)":"Opioid OD Death Rate (2016)", "Percent Change in Opioid Overdose Death Rate from Prior Year":"% Change in Opioid OD Death Rate from Prior Year (2016)"})

In [6]:
opOD_2012 = op_2012_rn[["Opioid OD Death Rate (2012)"]]
opOD_2013 = op_2013_rn[["Opioid OD Death Rate (2013)"]]
opOD_2014 = op_2014_rn[["Opioid OD Death Rate (2014)"]]
opOD_2015 = op_2015_rn[["Opioid OD Death Rate (2015)"]]
opOD_2016 = op_2016_rn[["Opioid OD Death Rate (2016)"]]

In [7]:
merge1 = pd.merge(opOD_2012, opOD_2013, on="Location")
merge2 = pd.merge(merge1, opOD_2014, on="Location")
merge3 = pd.merge(merge2, opOD_2015, on="Location")
OD_merge_table = pd.merge(merge3, opOD_2016, on="Location")
OD_merge_table

,Opioid OD Death Rate (2012),Opioid OD Death Rate (2013),Opioid OD Death Rate (2014),Opioid OD Death Rate (2015),Opioid OD Death Rate (2016)
Location,,,,,
United States,7.4,7.9,9.0,10.4,13.3
Arizona,8.2,8.2,8.8,10.2,11.4
Colorado,7.7,8,9.4,8.7,9.5
Florida,6.9,6.6,7.2,9.4,14.4
Washington,9.7,8.9,9.2,9.3,9.4

In [8]:
opP_2012 = op_2012_rn[["% Change in Opioid OD Death Rate from Prior Year (2012)"]]
opP_2013 = op_2013_rn[["% Change in Opioid OD Death Rate from Prior Year (2013)"]]
opP_2014 = op_2014_rn[["% Change in Opioid OD Death Rate from Prior Year (2014)"]]
opP_2015 = op_2015_rn[["% Change in Opioid OD Death Rate from Prior Year (2015)"]]
opP_2016 = op_2016_rn[["% Change in Opioid OD Death Rate from Prior Year (2016)"]]

In [9]:
mergeP1 = pd.merge(opP_2012, opP_2013, on="Location")
mergeP2 = pd.merge(mergeP1, opP_2014, on="Location")
mergeP3 = pd.merge(mergeP2, opP_2015, on="Location")
P_merge_table = pd.merge(mergeP3, opP_2016, on="Location")
P_merge_table

,% Change in Opioid OD Death Rate from Prior Year (2012),% Change in Opioid OD Death Rate from Prior Year (2013),% Change in Opioid OD Death Rate from Prior Year (2014),% Change in Opioid OD Death Rate from Prior Year (2015),% Change in Opioid OD Death Rate from Prior Year (2016)
Location,,,,,
United States,1.40%,7.00%,14.00%,15.60%,28.00%
Arizona,-6.80%,0.00%,7.00%,15.90%,12.00%
Colorado,-3.80%,4.00%,18.00%,-7.40%,9.00%
Florida,-17.90%,-4.00%,9.00%,30.60%,53.00%
Washington,-2.00%,-8.00%,3.00%,1.10%,1.00%