In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

opioid_file_2013 = "Opioid raw_data (2013).csv"

opioid_data_2013 = pd.read_csv(opioid_file_2013)

In [2]:
opioid_data_2013.head()

,Location,Opioid Overdose Death Rate (Age-Adjusted),All Drug Overdose Death Rate (Age-Adjusted),Percent Change in Opioid Overdose Death Rate from Prior Year,Percent Change in All Drug Overdose Death Rate from Prior Year
0,United States,7.9,13.8,0.07,0.05
1,Alabama,3.5,12.7,-0.03,0.05
2,Alaska,9.2,14.4,-0.15,-0.17
3,Arizona,8.2,18.7,0,0.06
4,Arkansas,5.6,11.1,-0.07,-0.15

In [3]:
opioid_df_2013 = opioid_data_2013.dropna()
opioid_df_2013.head()

,Location,Opioid Overdose Death Rate (Age-Adjusted),All Drug Overdose Death Rate (Age-Adjusted),Percent Change in Opioid Overdose Death Rate from Prior Year,Percent Change in All Drug Overdose Death Rate from Prior Year
0,United States,7.9,13.8,0.07,0.05
1,Alabama,3.5,12.7,-0.03,0.05
2,Alaska,9.2,14.4,-0.15,-0.17
3,Arizona,8.2,18.7,0,0.06
4,Arkansas,5.6,11.1,-0.07,-0.15

In [4]:
op_df_2013 = opioid_df_2013.set_index("Location")
op_df_2013.head()

,Opioid Overdose Death Rate (Age-Adjusted),All Drug Overdose Death Rate (Age-Adjusted),Percent Change in Opioid Overdose Death Rate from Prior Year,Percent Change in All Drug Overdose Death Rate from Prior Year
Location,,,,
United States,7.9,13.8,0.07,0.05
Alabama,3.5,12.7,-0.03,0.05
Alaska,9.2,14.4,-0.15,-0.17
Arizona,8.2,18.7,0,0.06
Arkansas,5.6,11.1,-0.07,-0.15

In [5]:
op_df_2013_st = op_df_2013.loc[["United States","Arizona", "Colorado", "Florida", "Washington"]]

In [6]:
op_df_2013_st

,Opioid Overdose Death Rate (Age-Adjusted),All Drug Overdose Death Rate (Age-Adjusted),Percent Change in Opioid Overdose Death Rate from Prior Year,Percent Change in All Drug Overdose Death Rate from Prior Year
Location,,,,
United States,7.9,13.8,0.07,0.05
Arizona,8.2,18.7,0,0.06
Colorado,8,15.5,0.04,0.03
Florida,6.6,12.6,-0.04,-0.05
Washington,8.9,13.4,-0.08,-0.02

In [7]:
op_df_2013_st[["Opioid Overdose Death Rate (Age-Adjusted)","Percent Change in Opioid Overdose Death Rate from Prior Year"]]

,Opioid Overdose Death Rate (Age-Adjusted),Percent Change in Opioid Overdose Death Rate from Prior Year
Location,,
United States,7.9,0.07
Arizona,8.2,0
Colorado,8,0.04
Florida,6.6,-0.04
Washington,8.9,-0.08